### ISSUE TITLE
Not working on heroku

### ISSUE THREAD

**Issue by joaquin102** [didierfranc/parse-dashboard-heroku#1]
Hey! I just clicked the deploy on heroku button, then i filled up all credentials and at the end the parse dashboard comes up but it says 'Unable to connect to server'.

I downloaded the folder to my local machine and it works but for some reason it doesn't on heroku.

Does anybody has the same issue?

Thank you!

![screen shot 2017-02-05 at 11 55 05 am](https://cloud.githubusercontent.com/assets/8617373/22629403/2023cd62-eb9a-11e6-8e1c-48ec0ce53965.png)

**Comment by didierfranc** [comment]
You must entered full url for your server
